### ISSUE TITLE
Failed to install

### ISSUE THREAD

**Issue by 1vory** [fja05680/pinkfish#86]
Hi, tried to install pinkfish

via clone and install
```
Downloading https://files.pythonhosted.org/packages/6e/1f/91144ba78dccea567a6466262922786ffc97be1e9b06ed9574ef0edc11e1/scipy-1.11.4.tar.gz#sha256=90a2b78e7f5733b9de748f589f09225013685f9b218275257f8a8168ededaeaa
Best match: scipy 1.11.4
Processing scipy-1.11.4.tar.gz
error: Couldn't find a setup script in /var/folders/gf/7hh60mmd69z25h26k3_03fwc0000gq/T/easy_install-nv2fruvy/scipy-1.11.4.tar.gz
```

via pip
`Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1`

How can I fix that? 

Thanks!

**Comment by fja05680** [comment]
Hello,

What OS are you using?

**Comment by 1vory** [comment]
Sorry :). Mac OS Sonoma Am 12.06.2024 um 19:33 schrieb Farrell Aultman ***@***.***>:﻿
Hello,
What OS are you using?

**Comment by fja05680** [comment]
Ubuntu, but others have got it working even on windows.  Try the developer instructions which I modified to remove the TA lib install which you don't really need:

git clone https://github.com/fja05680/pinkfish.git
cd pinkfish

# Create virtual Python environment

python -m venv venv
source venv/bin/activate

# Install pinkfish
python setup.py install

# Create shared data cache directory (optional)
mkdir $HOME/data
echo [global] > $HOME/.pinkfish
echo base_dir = $HOME >> $HOME/.pinkfish

**Comment by 1vory** [comment]
thanks for the quick reply! as it took me quite a bit to configure my env the way things are running right now. I'd rather avoid to deinstall TA Lib and also run a new env if that is possible. 

Digget a bit deeper on google etc. and seems like there is an incompatibility with PyYAML and cython. This checks out with the error message I got.

As I am quite a novice at coding, any hint how I can fix that? Just find resolutions for other packages, which I am not able to apply to the pf installation 

Thanks

```
Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      running egg_info
      writing lib/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/Users/x1ang/anaconda3/envs/Indie_v1/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/x1ang/anaconda3/envs/Indie_v1/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/x1ang/anaconda3/envs/Indie_v1/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 550, in run
          self.add_defaults()
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 250, in add_defaults
          self._add_defaults_ext()
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/_distutils/command/sdist.py", line 335, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
        File "<string>", line 204, in get_source_files
        File "/private/var/folders/69/8tlxqxyx4m12r812m_9gnp6m0000gn/T/pip-build-env-bs3ylncj/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
```

**Comment by fja05680** [comment]
The easiest and surest route is to run pinkfish in a linux VM.  It is not hard to do if you have never done that before.  I recommend vmware player and ubuntu 22.04.  The instructions here will definitely work with that setup:
https://fja05680.github.io/pinkfish/

In any case, it's a good practice to use a new python virtual environment with each python project you install.  It's the only way to be sure that your dependencies are correct and that you don't mess up other python projects on your computer.

**Comment by fja05680** [comment]
Closing this issue.
