### ISSUE TITLE
installing issue with python 3.3

### ISSUE THREAD

**Issue by davidhuang123** [fja05680/pinkfish#9]
Hello, 

I am trying to install pinkfish, according to PyPI, it works with Python 3.3(https://pypi.org/project/pinkfish/).

But when i try to install it in python 3.3 environment it show the following error:
Does it work with higher python version now?

py33) C:\Users\david>pip install pinkfish
Traceback (most recent call last):
  File "c:\users\david\anaconda3\envs\py33\lib\runpy.py", line 160, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\users\david\anaconda3\envs\py33\lib\runpy.py", line 73, in _run_code
    exec(code, run_globals)
  File "C:\Users\david\Anaconda3\envs\py33\Scripts\pip.exe\__main__.py", line 5, in <module>
  File "c:\users\david\anaconda3\envs\py33\lib\site-packages\pip\_internal\__init__.py", line 40, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "c:\users\david\anaconda3\envs\py33\lib\site-packages\pip\_internal\cli\autocompletion.py", line 8, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "c:\users\david\anaconda3\envs\py33\lib\site-packages\pip\_internal\cli\main_parser.py", line 8, in <module>
    from pip._internal.cli import cmdoptions
  File "c:\users\david\anaconda3\envs\py33\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 22, in <module>
    from pip._internal.utils.hashes import STRONG_HASHES
  File "c:\users\david\anaconda3\envs\py33\lib\site-packages\pip\_internal\utils\hashes.py", line 10, in <module>
    from pip._internal.utils.misc import read_chunks
  File "c:\users\david\anaconda3\envs\py33\lib\site-packages\pip\_internal\utils\misc.py", line 20, in <module>
    from pip._vendor import pkg_resources
  File "c:\users\david\anaconda3\envs\py33\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.4 or later is required")
RuntimeError: Python 3.4 or later is required

**Comment by fja05680** [comment]
Please install via the instructions below:

http://fja05680.github.io/pinkfish/

The version available through pip is very old.  In term of python 3, I
haven't tried it but others have and it's reported to work.

Farrell

**Comment by davidhuang123** [comment]
Thanks for the reply. The instruction provided is for Linux platform.

Is there a instruction working for Windows 10 or Anaconda?

I installed it using pip install pinkfish in Anaconda environment in Win 10 with python3.3 and 3.5, it always has some issues when running the sample code.

**Comment by fja05680** [comment]
I don't know how others have got it to work on Windows.  I recommend
installing vm player and xubuntu 18.04.  Both are free, and then you can
follow the instructions exactly and everything will work.  It's actually
not very difficult; you can find YouTube videos and how to do this.  I
can't offer direct assistance for Windows or Mac due to lack of time and
personal interest.

Farrell

**Comment by fja05680** [comment]
I'll try to contact someone I know has got it to work directly under
Windows and see if they can provide the install instructions.  If they do,
I'll forward it to you.

**Comment by simongarisch** [comment]
Hi there. I've got it to run on windows. Just added a requirements.txt file that lists the versions I'm running under (see pull requests). The TA-lib installation requires an extra step: You'll have to install from the wheel here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#ta-lib

More info here https://github.com/mrjbq7/ta-lib/issues/156

**Comment by davidhuang123** [comment]
Thanks for the clearification. I am glad there is a simple and flexible library like this.
I will try the way you mentioned to install.

**Comment by davidhuang123** [comment]
I can successfully install it after running Ubuntu on Windows 10 following original  instructions .
 http://localhost:8888/?token=d2892f538ffae49e1ef1e3421ce07b163df02241482b6de7

**Comment by fja05680** [comment]
Great, glad you got it to work!
